import { TLDrawGroupNode, TLDrawShapeNode, TlDrawFile } from './tldraw-schema';

export const tldrawEmptyFile: TlDrawFile = {
  tldrawFileFormatVersion: 1,
  schema: {
    schemaVersion: 2,
    sequences: {
      'com.tldraw.store': 4,
      'com.tldraw.asset': 1,
      'com.tldraw.camera': 1,
      'com.tldraw.document': 2,
      'com.tldraw.instance': 25,
      'com.tldraw.instance_page_state': 5,
      'com.tldraw.page': 1,
      'com.tldraw.instance_presence': 5,
      'com.tldraw.pointer': 1,
      'com.tldraw.shape': 4,
      'com.tldraw.asset.bookmark': 1,
      'com.tldraw.asset.image': 3,
      'com.tldraw.asset.video': 3,
      'com.tldraw.shape.group': 0,
      'com.tldraw.shape.text': 2,
      'com.tldraw.shape.bookmark': 2,
      'com.tldraw.shape.draw': 1,
      'com.tldraw.shape.geo': 8,
      'com.tldraw.shape.note': 6,
      'com.tldraw.shape.line': 4,
      'com.tldraw.shape.frame': 0,
      'com.tldraw.shape.arrow': 4,
      'com.tldraw.shape.highlight': 0,
      'com.tldraw.shape.embed': 4,
      'com.tldraw.shape.image': 3,
      'com.tldraw.shape.video': 2,
      'com.tldraw.binding.arrow': 0,
    },
  },
  records: [
    {
      gridSize: 10,
      name: '',
      meta: {},
      id: 'document:document',
      typeName: 'document',
    },
    {
      id: 'pointer:pointer',
      typeName: 'pointer',
      x: -7.646484375,
      y: 98.3125,
      lastActivityTimestamp: 1717744146620,
      meta: {},
    },
    {
      meta: {},
      id: 'page:page',
      name: 'Page 1',
      index: 'a1',
      typeName: 'page',
    },
    {
      followingUserId: null,
      opacityForNextShape: 1,
      stylesForNextShape: { 'tldraw:geo': 'rectangle' },
      brush: null,
      scribbles: [],
      cursor: { type: 'default', rotation: 0 },
      isFocusMode: false,
      exportBackground: true,
      isDebugMode: false,
      isToolLocked: false,
      screenBounds: { x: 0, y: 0, w: 1502, h: 809 },
      insets: [false, false, false, false],
      zoomBrush: null,
      isGridMode: false,
      isPenMode: false,
      chatMessage: '',
      isChatting: false,
      highlightedUserIds: [],
      isFocused: true,
      devicePixelRatio: 2,
      isCoarsePointer: false,
      isHoveringCanvas: true,
      openMenus: [],
      isChangingStyle: false,
      isReadonly: false,
      meta: {},
      duplicateProps: null,
      id: 'instance:instance',
      currentPageId: 'page:page',
      typeName: 'instance',
    },
    {
      editingShapeId: null,
      croppingShapeId: null,
      selectedShapeIds: ['shape:mQ5X_Xg9gO4Zp-scblr77'],
      hoveredShapeId: null,
      erasingShapeIds: [],
      hintingShapeIds: [],
      focusedGroupId: null,
      meta: {},
      id: 'instance_page_state:page:page',
      pageId: 'page:page',
      typeName: 'instance_page_state',
    },
    {
      x: 171.708984375,
      y: 51.62109375,
      z: 1,
      meta: {},
      id: 'camera:page:page',
      typeName: 'camera',
    },
  ],
};

export const tldrawShapeNode: TLDrawShapeNode = {
  x: 415.982421875,
  y: 212.4765625,
  rotation: 0,
  isLocked: false,
  opacity: 1,
  meta: {},
  id: 'shape:12344',
  type: 'geo',
  props: {
    w: 141.75,
    h: 158.6328125,
    geo: 'rectangle',
    color: 'black',
    labelColor: 'black',
    fill: 'none',
    dash: 'draw',
    size: 'm',
    font: 'draw',
    text: '',
    align: 'middle',
    verticalAlign: 'middle',
    growY: 0,
    url: '',
  },
  parentId: 'page:page',
  index: 'aaa1222',
  typeName: 'shape',
};

export const tldrawEmptyGroupNode: TLDrawGroupNode = {
  x: 335.248046875,
  y: 265.51953125,
  rotation: 0,
  isLocked: false,
  opacity: 1,
  meta: {},
  id: 'shape:P97gvLhIvgUIz4HzuKWYA',
  type: 'group',
  parentId: 'page:page',
  index: 'a1',
  props: {},
  typeName: 'shape',
};
