name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: nx build my-app

      - name: Deploy to Cloudflare Pages
        uses: nxext/cloudflare-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API }}
          zoneId: ${{ secrets.CLOUDFLARE_ZONEID }}
          route: flowbasedprogramming.nl
